version: "3.9"
services:
  todo_postgres:
    image: postgres
    platform: linux/amd64
    container_name: todo_postgres
    environment:
      POSTGRES_PASSWORD: todo
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PORT: 5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:z
  todo:
    build: .
    platform: linux/amd64
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/var/www/todo:z
    ports:
      - "3000:3000"
    depends_on:
      - todo_postgres