require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/socials", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Social. As you add validations to Social, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Social.create! valid_attributes
      get socials_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      social = Social.create! valid_attributes
      get social_url(social)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_social_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      social = Social.create! valid_attributes
      get edit_social_url(social)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Social" do
        expect {
          post socials_url, params: { social: valid_attributes }
        }.to change(Social, :count).by(1)
      end

      it "redirects to the created social" do
        post socials_url, params: { social: valid_attributes }
        expect(response).to redirect_to(social_url(Social.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Social" do
        expect {
          post socials_url, params: { social: invalid_attributes }
        }.to change(Social, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post socials_url, params: { social: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested social" do
        social = Social.create! valid_attributes
        patch social_url(social), params: { social: new_attributes }
        social.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the social" do
        social = Social.create! valid_attributes
        patch social_url(social), params: { social: new_attributes }
        social.reload
        expect(response).to redirect_to(social_url(social))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        social = Social.create! valid_attributes
        patch social_url(social), params: { social: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested social" do
      social = Social.create! valid_attributes
      expect {
        delete social_url(social)
      }.to change(Social, :count).by(-1)
    end

    it "redirects to the socials list" do
      social = Social.create! valid_attributes
      delete social_url(social)
      expect(response).to redirect_to(socials_url)
    end
  end
end
